"""sync models with database

Revision ID: 8f6f07d6f8c2
Revises: 63244b19c896
Create Date: 2025-11-11 23:51:12.580581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6f07d6f8c2'
down_revision: Union[str, None] = '63244b19c896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('product_parent', sa.String(length=20), nullable=False),
    sa.Column('product_title', sa.String(length=500), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('review_headline', sa.String(length=500), nullable=True),
    sa.Column('review_body', sa.Text(), nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('vine', sa.Boolean(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.String(length=5), nullable=True),
    sa.Column('review_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_date', 'source_reviews', ['product_category', 'review_date'], unique=False)
    op.create_index('idx_category_rating', 'source_reviews', ['product_category', 'star_rating'], unique=False)
    op.create_index('idx_category_verified', 'source_reviews', ['product_category', 'verified_purchase'], unique=False)
    op.create_index('idx_product_rating', 'source_reviews', ['product_id', 'star_rating'], unique=False)
    op.create_index('idx_verified_rating', 'source_reviews', ['verified_purchase', 'star_rating'], unique=False)
    op.create_index(op.f('ix_source_reviews_id'), 'source_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_source_reviews_product_category'), 'source_reviews', ['product_category'], unique=False)
    op.create_index(op.f('ix_source_reviews_product_id'), 'source_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_source_reviews_review_date'), 'source_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_source_reviews_review_id'), 'source_reviews', ['review_id'], unique=True)
    op.create_index(op.f('ix_source_reviews_star_rating'), 'source_reviews', ['star_rating'], unique=False)
    op.create_index(op.f('ix_source_reviews_verified_purchase'), 'source_reviews', ['verified_purchase'], unique=False)
    op.alter_column('chat_analytics', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_conversations', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('demographics', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('demographics', 'ai_tools_used',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('demographics', 'workflow_tools_used',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('demographics', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('demographics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('demographics', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('demographics_session_id_key'), 'demographics', type_='unique')
    op.drop_index(op.f('idx_demographics_age'), table_name='demographics')
    op.drop_index(op.f('idx_demographics_ai_exp'), table_name='demographics')
    op.drop_index(op.f('idx_demographics_completed_at'), table_name='demographics')
    op.drop_index(op.f('idx_demographics_education'), table_name='demographics')
    op.drop_index(op.f('idx_demographics_programming_exp'), table_name='demographics')
    op.drop_index(op.f('idx_demographics_session_id'), table_name='demographics')
    op.drop_index(op.f('idx_demographics_technical_role'), table_name='demographics')
    op.create_index(op.f('ix_demographics_id'), 'demographics', ['id'], unique=False)
    op.create_index(op.f('ix_demographics_session_id'), 'demographics', ['session_id'], unique=True)
    op.drop_constraint(op.f('demographics_session_id_fkey'), 'demographics', type_='foreignkey')
    op.create_foreign_key(None, 'demographics', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_execution_checkpoints_id'), 'execution_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    op.alter_column('execution_summaries', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('execution_summaries', 'task1_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('execution_summaries', 'task2_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('execution_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('execution_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_execution_summaries_session'), table_name='execution_summaries')
    op.create_index(op.f('ix_execution_summaries_id'), 'execution_summaries', ['id'], unique=False)
    op.create_unique_constraint(None, 'execution_summaries', ['session_id'])
    op.drop_constraint(op.f('execution_summaries_session_id_fkey'), 'execution_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'execution_summaries', 'sessions', ['session_id'], ['session_id'])
    op.drop_index(op.f('ix_workflow_executions_condition'), table_name='executions')
    op.drop_index(op.f('ix_workflow_executions_session_id'), table_name='executions')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='executions')
    op.create_index(op.f('ix_executions_condition'), 'executions', ['condition'], unique=False)
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_session_id'), 'executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_executions_started_at'), 'executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.alter_column('interactions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('interactions', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'interactions', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.alter_column('session_errors', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_session_errors_error_timestamp'), 'session_errors', ['error_timestamp'], unique=False)
    op.create_index(op.f('ix_session_errors_error_type'), 'session_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_session_errors_resolved'), 'session_errors', ['resolved'], unique=False)
    op.create_foreign_key(None, 'session_errors', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.alter_column('sessions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sessions', 'has_demographics',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_sessions_connection_status'), 'sessions', ['connection_status'], unique=False)
    op.create_index(op.f('ix_sessions_has_demographics'), 'sessions', ['has_demographics'], unique=False)
    op.alter_column('shoes_reviews', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_shoes_is_malformed'), table_name='shoes_reviews')
    op.drop_index(op.f('idx_shoes_product_id'), table_name='shoes_reviews')
    op.drop_index(op.f('idx_shoes_review_date'), table_name='shoes_reviews')
    op.drop_index(op.f('idx_shoes_star_rating'), table_name='shoes_reviews')
    op.drop_index(op.f('idx_shoes_verified_purchase'), table_name='shoes_reviews')
    op.create_index('idx_shoes_helpful', 'shoes_reviews', ['product_id', 'helpful_votes'], unique=False)
    op.create_index('idx_shoes_product_date', 'shoes_reviews', ['product_id', 'review_date'], unique=False)
    op.create_index('idx_shoes_product_rating_date', 'shoes_reviews', ['product_id', 'star_rating', 'review_date'], unique=False)
    op.create_index('idx_shoes_quality', 'shoes_reviews', ['is_malformed', 'is_main_product'], unique=False)
    op.create_index('idx_shoes_verified_rating', 'shoes_reviews', ['verified_purchase', 'star_rating'], unique=False)
    op.create_index(op.f('ix_shoes_reviews_is_malformed'), 'shoes_reviews', ['is_malformed'], unique=False)
    op.create_index(op.f('ix_shoes_reviews_product_id'), 'shoes_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_shoes_reviews_review_date'), 'shoes_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_shoes_reviews_star_rating'), 'shoes_reviews', ['star_rating'], unique=False)
    op.create_index(op.f('ix_shoes_reviews_verified_purchase'), 'shoes_reviews', ['verified_purchase'], unique=False)
    op.alter_column('survey_responses', 'participant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Participant ID as INTEGER to match sessions table',
               existing_nullable=False)
    op.alter_column('survey_responses', 'session_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Foreign key to sessions.session_id (VARCHAR format)',
               existing_nullable=False)
    op.alter_column('survey_responses', 'duration_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Auto-calculated duration in seconds',
               existing_nullable=True)
    op.alter_column('survey_responses', 'nasa_tlx_performance',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='NASA-TLX Performance: 0=Perfect to 100=Failure (reverse-coded in analysis)',
               existing_nullable=True)
    op.drop_index(op.f('idx_survey_responses_completed'), table_name='survey_responses')
    op.drop_index(op.f('idx_survey_responses_condition'), table_name='survey_responses')
    op.drop_index(op.f('idx_survey_responses_participant'), table_name='survey_responses')
    op.drop_index(op.f('idx_survey_responses_session'), table_name='survey_responses')
    op.drop_index(op.f('idx_survey_responses_task'), table_name='survey_responses')
    op.create_index(op.f('ix_survey_responses_completed_at'), 'survey_responses', ['completed_at'], unique=False)
    op.create_index(op.f('ix_survey_responses_condition'), 'survey_responses', ['condition'], unique=False)
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    op.create_index(op.f('ix_survey_responses_participant_id'), 'survey_responses', ['participant_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_session_id'), 'survey_responses', ['session_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_task_number'), 'survey_responses', ['task_number'], unique=False)
    op.drop_constraint(op.f('fk_session'), 'survey_responses', type_='foreignkey')
    op.drop_table_comment(
        'survey_responses',
        existing_comment='Stores post-task survey responses including NASA-TLX, Likert scales, and open-ended feedback',
        schema=None
    )
    op.alter_column('wireless_reviews', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_wireless_is_malformed'), table_name='wireless_reviews')
    op.drop_index(op.f('idx_wireless_product_id'), table_name='wireless_reviews')
    op.drop_index(op.f('idx_wireless_review_date'), table_name='wireless_reviews')
    op.drop_index(op.f('idx_wireless_star_rating'), table_name='wireless_reviews')
    op.drop_index(op.f('idx_wireless_verified_purchase'), table_name='wireless_reviews')
    op.create_index('idx_wireless_helpful', 'wireless_reviews', ['product_id', 'helpful_votes'], unique=False)
    op.create_index('idx_wireless_product_date', 'wireless_reviews', ['product_id', 'review_date'], unique=False)
    op.create_index('idx_wireless_product_rating_date', 'wireless_reviews', ['product_id', 'star_rating', 'review_date'], unique=False)
    op.create_index('idx_wireless_quality', 'wireless_reviews', ['is_malformed', 'is_main_product'], unique=False)
    op.create_index('idx_wireless_verified_rating', 'wireless_reviews', ['verified_purchase', 'star_rating'], unique=False)
    op.create_index(op.f('ix_wireless_reviews_is_malformed'), 'wireless_reviews', ['is_malformed'], unique=False)
    op.create_index(op.f('ix_wireless_reviews_product_id'), 'wireless_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_wireless_reviews_review_date'), 'wireless_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_wireless_reviews_star_rating'), 'wireless_reviews', ['star_rating'], unique=False)
    op.create_index(op.f('ix_wireless_reviews_verified_purchase'), 'wireless_reviews', ['verified_purchase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wireless_reviews_verified_purchase'), table_name='wireless_reviews')
    op.drop_index(op.f('ix_wireless_reviews_star_rating'), table_name='wireless_reviews')
    op.drop_index(op.f('ix_wireless_reviews_review_date'), table_name='wireless_reviews')
    op.drop_index(op.f('ix_wireless_reviews_product_id'), table_name='wireless_reviews')
    op.drop_index(op.f('ix_wireless_reviews_is_malformed'), table_name='wireless_reviews')
    op.drop_index('idx_wireless_verified_rating', table_name='wireless_reviews')
    op.drop_index('idx_wireless_quality', table_name='wireless_reviews')
    op.drop_index('idx_wireless_product_rating_date', table_name='wireless_reviews')
    op.drop_index('idx_wireless_product_date', table_name='wireless_reviews')
    op.drop_index('idx_wireless_helpful', table_name='wireless_reviews')
    op.create_index(op.f('idx_wireless_verified_purchase'), 'wireless_reviews', ['verified_purchase'], unique=False)
    op.create_index(op.f('idx_wireless_star_rating'), 'wireless_reviews', ['star_rating'], unique=False)
    op.create_index(op.f('idx_wireless_review_date'), 'wireless_reviews', ['review_date'], unique=False)
    op.create_index(op.f('idx_wireless_product_id'), 'wireless_reviews', ['product_id'], unique=False)
    op.create_index(op.f('idx_wireless_is_malformed'), 'wireless_reviews', ['is_malformed'], unique=False)
    op.alter_column('wireless_reviews', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'survey_responses',
        'Stores post-task survey responses including NASA-TLX, Likert scales, and open-ended feedback',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_session'), 'survey_responses', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_survey_responses_task_number'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_session_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_participant_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_condition'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_completed_at'), table_name='survey_responses')
    op.create_index(op.f('idx_survey_responses_task'), 'survey_responses', ['task_number'], unique=False)
    op.create_index(op.f('idx_survey_responses_session'), 'survey_responses', ['session_id'], unique=False)
    op.create_index(op.f('idx_survey_responses_participant'), 'survey_responses', ['participant_id'], unique=False)
    op.create_index(op.f('idx_survey_responses_condition'), 'survey_responses', ['condition'], unique=False)
    op.create_index(op.f('idx_survey_responses_completed'), 'survey_responses', ['completed_at'], unique=False)
    op.alter_column('survey_responses', 'nasa_tlx_performance',
               existing_type=sa.INTEGER(),
               comment='NASA-TLX Performance: 0=Perfect to 100=Failure (reverse-coded in analysis)',
               existing_nullable=True)
    op.alter_column('survey_responses', 'duration_seconds',
               existing_type=sa.INTEGER(),
               comment='Auto-calculated duration in seconds',
               existing_nullable=True)
    op.alter_column('survey_responses', 'session_id',
               existing_type=sa.VARCHAR(),
               comment='Foreign key to sessions.session_id (VARCHAR format)',
               existing_nullable=False)
    op.alter_column('survey_responses', 'participant_id',
               existing_type=sa.INTEGER(),
               comment='Participant ID as INTEGER to match sessions table',
               existing_nullable=False)
    op.drop_index(op.f('ix_shoes_reviews_verified_purchase'), table_name='shoes_reviews')
    op.drop_index(op.f('ix_shoes_reviews_star_rating'), table_name='shoes_reviews')
    op.drop_index(op.f('ix_shoes_reviews_review_date'), table_name='shoes_reviews')
    op.drop_index(op.f('ix_shoes_reviews_product_id'), table_name='shoes_reviews')
    op.drop_index(op.f('ix_shoes_reviews_is_malformed'), table_name='shoes_reviews')
    op.drop_index('idx_shoes_verified_rating', table_name='shoes_reviews')
    op.drop_index('idx_shoes_quality', table_name='shoes_reviews')
    op.drop_index('idx_shoes_product_rating_date', table_name='shoes_reviews')
    op.drop_index('idx_shoes_product_date', table_name='shoes_reviews')
    op.drop_index('idx_shoes_helpful', table_name='shoes_reviews')
    op.create_index(op.f('idx_shoes_verified_purchase'), 'shoes_reviews', ['verified_purchase'], unique=False)
    op.create_index(op.f('idx_shoes_star_rating'), 'shoes_reviews', ['star_rating'], unique=False)
    op.create_index(op.f('idx_shoes_review_date'), 'shoes_reviews', ['review_date'], unique=False)
    op.create_index(op.f('idx_shoes_product_id'), 'shoes_reviews', ['product_id'], unique=False)
    op.create_index(op.f('idx_shoes_is_malformed'), 'shoes_reviews', ['is_malformed'], unique=False)
    op.alter_column('shoes_reviews', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_sessions_has_demographics'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_connection_status'), table_name='sessions')
    op.alter_column('sessions', 'has_demographics',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sessions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'session_errors', type_='foreignkey')
    op.drop_index(op.f('ix_session_errors_resolved'), table_name='session_errors')
    op.drop_index(op.f('ix_session_errors_error_type'), table_name='session_errors')
    op.drop_index(op.f('ix_session_errors_error_timestamp'), table_name='session_errors')
    op.alter_column('session_errors', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.alter_column('interactions', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interactions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index(op.f('ix_executions_started_at'), table_name='executions')
    op.drop_index(op.f('ix_executions_session_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_condition'), table_name='executions')
    op.create_index(op.f('ix_workflow_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_started_at'), 'executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_session_id'), 'executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_condition'), 'executions', ['condition'], unique=False)
    op.drop_constraint(None, 'execution_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('execution_summaries_session_id_fkey'), 'execution_summaries', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'execution_summaries', type_='unique')
    op.drop_index(op.f('ix_execution_summaries_id'), table_name='execution_summaries')
    op.create_index(op.f('idx_execution_summaries_session'), 'execution_summaries', ['session_id'], unique=False)
    op.alter_column('execution_summaries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('execution_summaries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('execution_summaries', 'task2_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_summaries', 'task1_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('execution_summaries', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_checkpoints_id'), table_name='execution_checkpoints')
    op.drop_constraint(None, 'demographics', type_='foreignkey')
    op.create_foreign_key(op.f('demographics_session_id_fkey'), 'demographics', 'sessions', ['session_id'], ['session_id'])
    op.drop_index(op.f('ix_demographics_session_id'), table_name='demographics')
    op.drop_index(op.f('ix_demographics_id'), table_name='demographics')
    op.create_index(op.f('idx_demographics_technical_role'), 'demographics', ['technical_role'], unique=False)
    op.create_index(op.f('idx_demographics_session_id'), 'demographics', ['session_id'], unique=False)
    op.create_index(op.f('idx_demographics_programming_exp'), 'demographics', ['programming_experience'], unique=False)
    op.create_index(op.f('idx_demographics_education'), 'demographics', ['education'], unique=False)
    op.create_index(op.f('idx_demographics_completed_at'), 'demographics', ['completed_at'], unique=False)
    op.create_index(op.f('idx_demographics_ai_exp'), 'demographics', ['ai_ml_experience'], unique=False)
    op.create_index(op.f('idx_demographics_age'), 'demographics', ['age'], unique=False)
    op.create_unique_constraint(op.f('demographics_session_id_key'), 'demographics', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('demographics', 'raw_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('demographics', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('demographics', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('demographics', 'workflow_tools_used',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('demographics', 'ai_tools_used',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('demographics', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_messages', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_conversations', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_analytics', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_source_reviews_verified_purchase'), table_name='source_reviews')
    op.drop_index(op.f('ix_source_reviews_star_rating'), table_name='source_reviews')
    op.drop_index(op.f('ix_source_reviews_review_id'), table_name='source_reviews')
    op.drop_index(op.f('ix_source_reviews_review_date'), table_name='source_reviews')
    op.drop_index(op.f('ix_source_reviews_product_id'), table_name='source_reviews')
    op.drop_index(op.f('ix_source_reviews_product_category'), table_name='source_reviews')
    op.drop_index(op.f('ix_source_reviews_id'), table_name='source_reviews')
    op.drop_index('idx_verified_rating', table_name='source_reviews')
    op.drop_index('idx_product_rating', table_name='source_reviews')
    op.drop_index('idx_category_verified', table_name='source_reviews')
    op.drop_index('idx_category_rating', table_name='source_reviews')
    op.drop_index('idx_category_date', table_name='source_reviews')
    op.drop_table('source_reviews')
    # ### end Alembic commands ###
